// Caliope 13
let worta = [""]
let speed = 0.5 * 1000
// angabe in sekunden
function z0() {
    //  basic.set_led_color(Colors.RED)
    basic.turnRgbLedOff()
    basic.pause(speed)
}

function z1() {
    basic.setLedColor(Colors.White)
    basic.pause(speed)
}

function connection() {
    z1()
    z1()
    z1()
    z1()
    z1()
    z1()
    z1()
    z1()
}

basic.forever(function on_forever() {
    let i: number;
    let gleichniss: boolean;
    let wort = [" "]
    for (i = 0; i < wort.length; i++) {
        if (wort[i] == worta[i]) {
            gleichniss = true
        } else {
            gleichniss = false
            break
        }
        
    }
    if (gleichniss == false) {
        connection()
        for (i = 0; i < wort.length; i++) {
            if (wort[i] == "!") {
                z0()
                z1()
                z0()
                z0()
                z0()
                z0()
                z1()
            } else if (wort[i] == "\"") {
                z0()
                z1()
                z0()
                z0()
                z1()
                z0()
                z0()
            } else if (wort[i] == " ") {
                z0()
                z0()
                z0()
                z1()
                z1()
                z1()
                z1()
            } else if (wort[i] == "#") {
                z0()
                z1()
                z0()
                z0()
                z1()
                z0()
                z1()
            } else if (wort[i] == "$") {
                z0()
                z1()
                z0()
                z0()
                z1()
                z0()
                z0()
            } else if (wort[i] == "%") {
                z0()
                z1()
                z0()
                z0()
                z1()
                z0()
                z1()
            } else if (wort[i] == "&") {
                z0()
                z1()
                z0()
                z0()
                z1()
                z1()
                z0()
            } else if (wort[i] == "'") {
                z0()
                z1()
                z0()
                z0()
                z1()
                z1()
                z1()
            } else if (wort[i] == "(") {
                z0()
                z1()
                z0()
                z1()
                z0()
                z0()
                z0()
            } else if (wort[i] == ")") {
                z0()
                z1()
                z0()
                z1()
                z0()
                z0()
                z1()
            } else if (wort[i] == "+") {
                z0()
                z1()
                z0()
                z1()
                z0()
                z1()
                z1()
            } else if (wort[i] == ",") {
                z0()
                z1()
                z0()
                z1()
                z1()
                z0()
                z0()
            } else if (wort[i] == ".") {
                z0()
                z1()
                z0()
                z1()
                z1()
                z1()
                z0()
            } else if (wort[i] == "/") {
                z0()
                z1()
                z0()
                z1()
                z1()
                z1()
                z1()
            } else if (wort[i] == "0") {
                z0()
                z1()
                z1()
                z0()
                z0()
                z0()
                z0()
            } else if (wort[i] == "1") {
                z0()
                z1()
                z1()
                z0()
                z0()
                z0()
                z1()
            } else if (wort[i] == "2") {
                z0()
                z1()
                z1()
                z0()
                z0()
                z1()
                z0()
            } else if (wort[i] == "3") {
                z0()
                z1()
                z1()
                z0()
                z0()
                z1()
                z1()
            } else if (wort[i] == "4") {
                z0()
                z1()
                z1()
                z0()
                z1()
                z0()
                z0()
            } else if (wort[i] == "5") {
                z0()
                z1()
                z1()
                z0()
                z1()
                z0()
                z1()
            } else if (wort[i] == "6") {
                z0()
                z1()
                z1()
                z0()
                z1()
                z1()
                z0()
            } else if (wort[i] == "7") {
                z0()
                z1()
                z1()
                z0()
                z1()
                z1()
                z1()
            } else if (wort[i] == "8") {
                z0()
                z1()
                z1()
                z1()
                z0()
                z0()
                z0()
            } else if (wort[i] == "9") {
                z0()
                z1()
                z1()
                z1()
                z0()
                z0()
                z1()
            } else if (wort[i] == ":") {
                z0()
                z1()
                z1()
                z1()
                z0()
                z1()
                z0()
            } else if (wort[i] == ";") {
                z0()
                z1()
                z1()
                z1()
                z0()
                z1()
                z1()
            } else if (wort[i] == "<") {
                z0()
                z1()
                z1()
                z1()
                z1()
                z0()
                z0()
            } else if (wort[i] == "=") {
                z0()
                z1()
                z1()
                z1()
                z1()
                z0()
                z1()
            } else if (wort[i] == "?") {
                z0()
                z1()
                z1()
                z1()
                z1()
                z1()
                z1()
            } else if (wort[i] == "@") {
                z1()
                z0()
                z0()
                z0()
                z0()
                z0()
                z0()
            } else if (wort[i] == "A") {
                z1()
                z0()
                z0()
                z0()
                z0()
                z0()
                z1()
            } else if (wort[i] == "B") {
                z1()
                z0()
                z0()
                z0()
                z0()
                z1()
                z0()
            } else if (wort[i] == "C") {
                z1()
                z0()
                z0()
                z0()
                z0()
                z1()
                z1()
            } else if (wort[i] == "D") {
                z1()
                z0()
                z0()
                z0()
                z1()
                z0()
                z0()
            } else if (wort[i] == "E") {
                z1()
                z0()
                z0()
                z0()
                z1()
                z0()
                z1()
            } else if (wort[i] == "F") {
                z1()
                z0()
                z0()
                z0()
                z1()
                z1()
                z0()
            } else if (wort[i] == "G") {
                z1()
                z0()
                z0()
                z0()
                z1()
                z1()
                z1()
            } else if (wort[i] == "H") {
                z1()
                z0()
                z0()
                z1()
                z0()
                z0()
                z0()
            } else if (wort[i] == "I") {
                z1()
                z0()
                z0()
                z1()
                z0()
                z0()
                z1()
            } else if (wort[i] == "J") {
                z1()
                z0()
                z0()
                z1()
                z0()
                z1()
                z0()
            } else if (wort[i] == "K") {
                z1()
                z0()
                z0()
                z1()
                z0()
                z1()
                z1()
            } else if (wort[i] == "L") {
                z1()
                z0()
                z0()
                z1()
                z1()
                z0()
                z0()
            } else if (wort[i] == "M") {
                z1()
                z0()
                z0()
                z1()
                z1()
                z0()
                z1()
            } else if (wort[i] == "N") {
                z1()
                z0()
                z0()
                z1()
                z1()
                z1()
                z0()
            } else if (wort[i] == "O") {
                z1()
                z0()
                z0()
                z1()
                z1()
                z1()
                z1()
            } else if (wort[i] == "P") {
                z1()
                z0()
                z1()
                z0()
                z0()
                z0()
                z0()
            } else if (wort[i] == "Q") {
                z1()
                z0()
                z1()
                z0()
                z0()
                z0()
                z1()
            } else if (wort[i] == "R") {
                z1()
                z0()
                z1()
                z0()
                z0()
                z1()
                z0()
            } else if (wort[i] == "S") {
                z1()
                z0()
                z1()
                z0()
                z0()
                z1()
                z1()
            } else if (wort[i] == "T") {
                z1()
                z0()
                z1()
                z0()
                z1()
                z0()
                z0()
            } else if (wort[i] == "U") {
                z1()
                z0()
                z1()
                z0()
                z1()
                z0()
                z1()
            } else if (wort[i] == "V") {
                z1()
                z0()
                z1()
                z0()
                z1()
                z1()
                z0()
            } else if (wort[i] == "W") {
                z1()
                z0()
                z1()
                z0()
                z1()
                z1()
                z1()
            } else if (wort[i] == "X") {
                z1()
                z0()
                z1()
                z1()
                z0()
                z0()
                z0()
            } else if (wort[i] == "Y") {
                z1()
                z0()
                z1()
                z1()
                z0()
                z0()
                z1()
            } else if (wort[i] == "Z") {
                z1()
                z0()
                z1()
                z1()
                z0()
                z1()
                z0()
            } else if (wort[i] == "[") {
                z1()
                z0()
                z1()
                z1()
                z0()
                z1()
                z1()
            } else if (wort[i] == "\\") {
                z1()
                z0()
                z1()
                z1()
                z1()
                z0()
                z0()
            } else if (wort[i] == "]") {
                z1()
                z0()
                z1()
                z1()
                z1()
                z0()
                z1()
            } else if (wort[i] == "^") {
                z1()
                z0()
                z1()
                z1()
                z1()
                z1()
                z0()
            } else if (wort[i] == "_") {
                z1()
                z0()
                z1()
                z1()
                z1()
                z1()
                z1()
            } else if (wort[i] == "`") {
                z1()
                z1()
                z0()
                z0()
                z0()
                z0()
                z0()
            } else if (wort[i] == "a") {
                z1()
                z1()
                z0()
                z0()
                z0()
                z0()
                z1()
            } else if (wort[i] == "b") {
                z1()
                z1()
                z0()
                z0()
                z0()
                z1()
                z0()
            } else if (wort[i] == "c") {
                z1()
                z1()
                z0()
                z0()
                z0()
                z1()
                z1()
            } else if (wort[i] == "d") {
                z1()
                z1()
                z0()
                z0()
                z1()
                z0()
                z0()
            } else if (wort[i] == "e") {
                z1()
                z1()
                z0()
                z0()
                z1()
                z0()
                z1()
            } else if (wort[i] == "f") {
                z1()
                z1()
                z0()
                z0()
                z1()
                z1()
                z0()
            } else if (wort[i] == "g") {
                z1()
                z1()
                z0()
                z0()
                z1()
                z1()
                z1()
            } else if (wort[i] == "h") {
                z1()
                z1()
                z0()
                z1()
                z0()
                z0()
                z0()
            } else if (wort[i] == "i") {
                z1()
                z1()
                z0()
                z1()
                z0()
                z0()
                z1()
            } else if (wort[i] == "j") {
                z1()
                z1()
                z0()
                z1()
                z0()
                z1()
                z0()
            } else if (wort[i] == "k") {
                z1()
                z1()
                z0()
                z1()
                z0()
                z1()
                z1()
            } else if (wort[i] == "l") {
                z1()
                z1()
                z0()
                z1()
                z1()
                z0()
                z0()
            } else if (wort[i] == "m") {
                z1()
                z1()
                z0()
                z1()
                z1()
                z0()
                z1()
            } else if (wort[i] == "n") {
                z1()
                z1()
                z0()
                z1()
                z1()
                z1()
                z0()
            } else if (wort[i] == "o") {
                z1()
                z1()
                z0()
                z1()
                z1()
                z1()
                z1()
            } else if (wort[i] == "p") {
                z1()
                z1()
                z1()
                z0()
                z0()
                z0()
                z0()
            } else if (wort[i] == "q") {
                z1()
                z1()
                z1()
                z0()
                z0()
                z0()
                z1()
            } else if (wort[i] == "r") {
                z1()
                z1()
                z1()
                z0()
                z0()
                z1()
                z0()
            } else if (wort[i] == "s") {
                z1()
                z1()
                z1()
                z0()
                z0()
                z1()
                z1()
            } else if (wort[i] == "t") {
                z1()
                z1()
                z1()
                z0()
                z1()
                z0()
                z0()
            } else if (wort[i] == "u") {
                z1()
                z1()
                z1()
                z0()
                z1()
                z0()
                z1()
            } else if (wort[i] == "v") {
                z1()
                z1()
                z1()
                z0()
                z1()
                z1()
                z0()
            } else if (wort[i] == "w") {
                z1()
                z1()
                z1()
                z0()
                z1()
                z1()
                z1()
            } else if (wort[i] == "x") {
                z1()
                z1()
                z1()
                z1()
                z0()
                z0()
                z0()
            } else if (wort[i] == "y") {
                z1()
                z1()
                z1()
                z1()
                z0()
                z0()
                z1()
            } else if (wort[i] == "z") {
                z1()
                z1()
                z1()
                z1()
                z0()
                z1()
                z0()
            } else if (wort[i] == "{") {
                z1()
                z1()
                z1()
                z1()
                z0()
                z1()
                z1()
            } else if (wort[i] == "|") {
                z1()
                z1()
                z1()
                z1()
                z1()
                z0()
                z0()
            } else if (wort[i] == "}") {
                z1()
                z1()
                z1()
                z1()
                z1()
                z0()
                z1()
            } else if (wort[i] == "~") {
                z1()
                z1()
                z1()
                z1()
                z1()
                z1()
                z0()
            }
            
        }
        for (i = 0; i < wort.length; i++) {
            worta[i] = wort[i]
        }
    } else {
        z0()
    }
    
})
