function z0() {
    basic.pause(500)
}

function z1() {
    basic.setLedColor(Colors.White)
    basic.pause(500)
    basic.turnRgbLedOff()
}

basic.forever(function on_forever() {
    let Wort = ["H", "a", "l", "l", "o"]
    for (let i = 0; i < Wort.length; i++) {
        if (Wort[i] == "!") {
            z0()
            z1()
            z0()
            z0()
            z0()
            z0()
            z1()
        } else if (Wort[i] == "\"") {
            z0()
            z1()
            z0()
            z0()
            z1()
            z0()
            z0()
        } else if (Wort[i] == "#") {
            z0()
            z1()
            z0()
            z0()
            z1()
            z0()
            z1()
        } else if (Wort[i] == "$") {
            z0()
            z1()
            z0()
            z0()
            z1()
            z0()
            z0()
        } else if (Wort[i] == "%") {
            z0()
            z1()
            z0()
            z0()
            z1()
            z0()
            z1()
        } else if (Wort[i] == "&") {
            z0()
            z1()
            z0()
            z0()
            z1()
            z1()
            z0()
        } else if (Wort[i] == "'") {
            z0()
            z1()
            z0()
            z0()
            z1()
            z1()
            z1()
        } else if (Wort[i] == "(") {
            z0()
            z1()
            z0()
            z1()
            z0()
            z0()
            z0()
        } else if (Wort[i] == ")") {
            z0()
            z1()
            z0()
            z1()
            z0()
            z0()
            z1()
        } else if (Wort[i] == "+") {
            z0()
            z1()
            z0()
            z1()
            z0()
            z1()
            z1()
        } else if (Wort[i] == ",") {
            z0()
            z1()
            z0()
            z1()
            z1()
            z0()
            z0()
        } else if (Wort[i] == ".") {
            z0()
            z1()
            z0()
            z1()
            z1()
            z1()
            z0()
        } else if (Wort[i] == "/") {
            z0()
            z1()
            z0()
            z1()
            z1()
            z1()
            z1()
        } else if (Wort[i] == "0") {
            z0()
            z1()
            z1()
            z0()
            z0()
            z0()
            z0()
        } else if (Wort[i] == "1") {
            z0()
            z1()
            z1()
            z0()
            z0()
            z0()
            z1()
        } else if (Wort[i] == "2") {
            z0()
            z1()
            z1()
            z0()
            z0()
            z1()
            z0()
        } else if (Wort[i] == "3") {
            z0()
            z1()
            z1()
            z0()
            z0()
            z1()
            z1()
        } else if (Wort[i] == "4") {
            z0()
            z1()
            z1()
            z0()
            z1()
            z0()
            z0()
        } else if (Wort[i] == "5") {
            z0()
            z1()
            z1()
            z0()
            z1()
            z0()
            z1()
        } else if (Wort[i] == "6") {
            z0()
            z1()
            z1()
            z0()
            z1()
            z1()
            z0()
        } else if (Wort[i] == "7") {
            z0()
            z1()
            z1()
            z0()
            z1()
            z1()
            z1()
        } else if (Wort[i] == "8") {
            z0()
            z1()
            z1()
            z1()
            z0()
            z0()
            z0()
        } else if (Wort[i] == "9") {
            z0()
            z1()
            z1()
            z1()
            z0()
            z0()
            z1()
        } else if (Wort[i] == ":") {
            z0()
            z1()
            z1()
            z1()
            z0()
            z1()
            z0()
        } else if (Wort[i] == ";") {
            z0()
            z1()
            z1()
            z1()
            z0()
            z1()
            z1()
        } else if (Wort[i] == "<") {
            z0()
            z1()
            z1()
            z1()
            z1()
            z0()
            z0()
        } else if (Wort[i] == "=") {
            z0()
            z1()
            z1()
            z1()
            z1()
            z0()
            z1()
        } else if (Wort[i] == "?") {
            z0()
            z1()
            z1()
            z1()
            z1()
            z1()
            z1()
        } else if (Wort[i] == "@") {
            z1()
            z0()
            z0()
            z0()
            z0()
            z0()
            z0()
        } else if (Wort[i] == "A") {
            z1()
            z0()
            z0()
            z0()
            z0()
            z0()
            z1()
        } else if (Wort[i] == "B") {
            z1()
            z0()
            z0()
            z0()
            z0()
            z1()
            z0()
        } else if (Wort[i] == "C") {
            z1()
            z0()
            z0()
            z0()
            z0()
            z1()
            z1()
        } else if (Wort[i] == "D") {
            z1()
            z0()
            z0()
            z0()
            z1()
            z0()
            z0()
        } else if (Wort[i] == "E") {
            z1()
            z0()
            z0()
            z0()
            z1()
            z0()
            z1()
        } else if (Wort[i] == "F") {
            z1()
            z0()
            z0()
            z0()
            z1()
            z1()
            z0()
        } else if (Wort[i] == "G") {
            z1()
            z0()
            z0()
            z0()
            z1()
            z1()
            z1()
        } else if (Wort[i] == "H") {
            z1()
            z0()
            z0()
            z1()
            z0()
            z0()
            z0()
        } else if (Wort[i] == "I") {
            z1()
            z0()
            z0()
            z1()
            z0()
            z0()
            z1()
        } else if (Wort[i] == "J") {
            z1()
            z0()
            z0()
            z1()
            z0()
            z1()
            z0()
        } else if (Wort[i] == "K") {
            z1()
            z0()
            z0()
            z1()
            z0()
            z1()
            z1()
        } else if (Wort[i] == "L") {
            z1()
            z0()
            z0()
            z1()
            z1()
            z0()
            z0()
        } else if (Wort[i] == "M") {
            z1()
            z0()
            z0()
            z1()
            z1()
            z0()
            z1()
        } else if (Wort[i] == "N") {
            z1()
            z0()
            z0()
            z1()
            z1()
            z1()
            z0()
        } else if (Wort[i] == "O") {
            z1()
            z0()
            z0()
            z1()
            z1()
            z1()
            z1()
        } else if (Wort[i] == "P") {
            z1()
            z0()
            z1()
            z0()
            z0()
            z0()
            z0()
        } else if (Wort[i] == "Q") {
            z1()
            z0()
            z1()
            z0()
            z0()
            z0()
            z1()
        } else if (Wort[i] == "R") {
            z1()
            z0()
            z1()
            z0()
            z0()
            z1()
            z0()
        } else if (Wort[i] == "S") {
            z1()
            z0()
            z1()
            z0()
            z0()
            z1()
            z1()
        } else if (Wort[i] == "T") {
            z1()
            z0()
            z1()
            z0()
            z1()
            z0()
            z0()
        } else if (Wort[i] == "U") {
            z1()
            z0()
            z1()
            z0()
            z1()
            z0()
            z1()
        } else if (Wort[i] == "V") {
            z1()
            z0()
            z1()
            z0()
            z1()
            z1()
            z0()
        } else if (Wort[i] == "W") {
            z1()
            z0()
            z1()
            z0()
            z1()
            z1()
            z1()
        } else if (Wort[i] == "X") {
            z1()
            z0()
            z1()
            z1()
            z0()
            z0()
            z0()
        } else if (Wort[i] == "Y") {
            z1()
            z0()
            z1()
            z1()
            z0()
            z0()
            z1()
        } else if (Wort[i] == "Z") {
            z1()
            z0()
            z1()
            z1()
            z0()
            z1()
            z0()
        } else if (Wort[i] == "[") {
            z1()
            z0()
            z1()
            z1()
            z0()
            z1()
            z1()
        } else if (Wort[i] == "\\") {
            z1()
            z0()
            z1()
            z1()
            z1()
            z0()
            z0()
        } else if (Wort[i] == "]") {
            z1()
            z0()
            z1()
            z1()
            z1()
            z0()
            z1()
        } else if (Wort[i] == "^") {
            z1()
            z0()
            z1()
            z1()
            z1()
            z1()
            z0()
        } else if (Wort[i] == "_") {
            z1()
            z0()
            z1()
            z1()
            z1()
            z1()
            z1()
        } else if (Wort[i] == "`") {
            z1()
            z1()
            z0()
            z0()
            z0()
            z0()
            z0()
        } else if (Wort[i] == "a") {
            z1()
            z1()
            z0()
            z0()
            z0()
            z0()
            z1()
        } else if (Wort[i] == "b") {
            z1()
            z1()
            z0()
            z0()
            z0()
            z1()
            z0()
        } else if (Wort[i] == "c") {
            z1()
            z1()
            z0()
            z0()
            z0()
            z1()
            z1()
        } else if (Wort[i] == "d") {
            z1()
            z1()
            z0()
            z0()
            z1()
            z0()
            z0()
        } else if (Wort[i] == "e") {
            z1()
            z1()
            z0()
            z0()
            z1()
            z0()
            z1()
        } else if (Wort[i] == "f") {
            z1()
            z1()
            z0()
            z0()
            z1()
            z1()
            z0()
        } else if (Wort[i] == "g") {
            z1()
            z1()
            z0()
            z0()
            z1()
            z1()
            z1()
        } else if (Wort[i] == "h") {
            z1()
            z1()
            z0()
            z1()
            z0()
            z0()
            z0()
        } else if (Wort[i] == "i") {
            z1()
            z1()
            z0()
            z1()
            z0()
            z0()
            z1()
        } else if (Wort[i] == "j") {
            z1()
            z1()
            z0()
            z1()
            z0()
            z1()
            z0()
        } else if (Wort[i] == "k") {
            z1()
            z1()
            z0()
            z1()
            z0()
            z1()
            z1()
        } else if (Wort[i] == "l") {
            z1()
            z1()
            z0()
            z1()
            z1()
            z0()
            z0()
        } else if (Wort[i] == "m") {
            z1()
            z1()
            z0()
            z1()
            z1()
            z0()
            z1()
        } else if (Wort[i] == "n") {
            z1()
            z1()
            z0()
            z1()
            z1()
            z1()
            z0()
        } else if (Wort[i] == "o") {
            z1()
            z1()
            z0()
            z1()
            z1()
            z1()
            z1()
        } else if (Wort[i] == "p") {
            z1()
            z1()
            z1()
            z0()
            z0()
            z0()
            z0()
        } else if (Wort[i] == "q") {
            z1()
            z1()
            z1()
            z0()
            z0()
            z0()
            z1()
        } else if (Wort[i] == "r") {
            z1()
            z1()
            z1()
            z0()
            z0()
            z1()
            z0()
        } else if (Wort[i] == "s") {
            z1()
            z1()
            z1()
            z0()
            z0()
            z1()
            z1()
        } else if (Wort[i] == "t") {
            z1()
            z1()
            z1()
            z0()
            z1()
            z0()
            z0()
        } else if (Wort[i] == "u") {
            z1()
            z1()
            z1()
            z0()
            z1()
            z0()
            z1()
        } else if (Wort[i] == "v") {
            z1()
            z1()
            z1()
            z0()
            z1()
            z1()
            z0()
        } else if (Wort[i] == "w") {
            z1()
            z1()
            z1()
            z0()
            z1()
            z1()
            z1()
        } else if (Wort[i] == "x") {
            z1()
            z1()
            z1()
            z1()
            z0()
            z0()
            z0()
        } else if (Wort[i] == "y") {
            z1()
            z1()
            z1()
            z1()
            z0()
            z0()
            z1()
        } else if (Wort[i] == "z") {
            z1()
            z1()
            z1()
            z1()
            z0()
            z1()
            z0()
        } else if (Wort[i] == "{") {
            z1()
            z1()
            z1()
            z1()
            z0()
            z1()
            z1()
        } else if (Wort[i] == "|") {
            z1()
            z1()
            z1()
            z1()
            z1()
            z0()
            z0()
        } else if (Wort[i] == "}") {
            z1()
            z1()
            z1()
            z1()
            z1()
            z0()
            z1()
        } else if (Wort[i] == "~") {
            z1()
            z1()
            z1()
            z1()
            z1()
            z1()
            z0()
        }
        
    }
})
